relativeURLs = true
title = "Ying Liang"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. candidate, Goethe University Frankfurt"
    logo = "Liang.png" 
    
